url: https://y7kim.github.io
baseurl: 

# Site settings
title: BrandGenie
email: your-email@domain.com
description: "The Core team at BrandGenie comes with more than a decade of varied expertise in the area of Media and Brand building. Headquartered out of Bangalore, we have strong network of associates across other cities."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Prarthna Vohra
  pic: 1
  position: Principal Consultant
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
- name: Sunaina Bajaj
  pic: 2
  position: Associate Consultant
  social:
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/BrandGenie
  - title: facebook
    url: http://facebook.com/BrandGenie

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: Bengaluru, Karnataka 

# Build settings
markdown: kramdown
permalink: pretty